<?php
declare(strict_types=1);

// Real nginx, private prefix/config/PID, and ephemeral ports: never load the host's includes.
spl_autoload_register(static function (string $class): void {
    if (str_starts_with($class, 'Scf\\')) {
        $path = dirname(__DIR__) . '/src/' . str_replace('\\', '/', substr($class, 4)) . '.php';
        if (is_file($path)) require_once $path;
    }
});
define('APP_DIR_NAME', 'startup_fixture');
define('SERVER_ROLE', 'master');
define('SERVER_RUN_ENV', 'dev');
define('APP_SRC_TYPE', 'dir');
$root = sys_get_temp_dir() . '/scf-nginx-startup-' . bin2hex(random_bytes(5));
mkdir($root . '/servers', 0700, true);
define('APP_UPDATE_DIR', $root . '/update');

function checkNginx(bool $ok, string $message): void {
    if (!$ok) throw new RuntimeException($message);
}
function testListener(): array {
    $socket = stream_socket_server('tcp://127.0.0.1:0', $errno, $error);
    checkNginx(is_resource($socket), $error);
    return [$socket, (int)substr(strrchr(stream_socket_get_name($socket, false), ':'), 1)];
}

class StartupFixtureGateway extends \Scf\Server\Gateway\GatewayServer {
    public function __construct(private int $testPort) {}
    public function nginxProxyModeEnabled(): bool { return true; }
    public function businessPort(): int { return $this->testPort; }
    public function serverConfig(): array { return ['gateway_nginx_reload' => true]; }
    public function resolvedGatewayNginxServerName(): string { return 'localhost'; }
    public function resolvedGatewayIngressProbeHost(?int $port = null): string { return 'localhost'; }
}

class StartupFixtureNginx extends \Scf\Server\Gateway\GatewayNginxProxyHandler {
    public string $answer = 'old';
    public bool $invalid = false;
    public int $extraListenPort = 0;
    public function __construct(string $root, string $binary, int $port) {
        parent::__construct(new StartupFixtureGateway($port), new \Scf\Server\Gateway\AppInstanceManager(
            new \Scf\Server\Gateway\UpstreamRegistry($root . '/registry.json')
        ));
        $this->nginxRuntimeMeta = ['bin' => $binary, 'conf_path' => $root . '/nginx.conf',
            'conf_dir' => $root . '/servers', 'pid_path' => $root . '/nginx.pid'];
    }
    protected function renderGlobalConfig(): string { return "# fixture global\n"; }
    protected function renderUpstreamConfig(): string { return "# fixture upstream\n"; }
    protected function renderServerConfig(): string {
        return 'server { listen 127.0.0.1:' . $this->gateway->businessPort() . '; server_name localhost; '
            . ($this->invalid ? 'invalid_directive on; ' : '')
            . ($this->extraListenPort > 0 ? 'listen 127.0.0.1:' . $this->extraListenPort . '; ' : '')
            . 'location = /slow { limit_rate 512; return 200 "' . str_repeat($this->answer . '-', 512) . '"; } '
            . 'location / { return 200 "' . $this->answer . '"; } }' . "\n";
    }
    protected function activeInstances(): array { return []; }
    protected function nginxServerFileExists(): bool { return true; }
    public function warmup(): array { return $this->warmupRuntimeMeta(true); }
}

$binary = getenv('SCF_TEST_NGINX') ?: '/opt/homebrew/bin/nginx';
checkNginx(is_executable($binary), 'Set SCF_TEST_NGINX to a real nginx binary');
[$occupied, $stalePort] = testListener();
[$available, $port] = testListener();
fclose($available);
[$unused, $deadPort] = testListener();
fclose($unused);
[$liveBackend, $liveBackendPort] = testListener();
[$unused, $livePort] = testListener();
fclose($unused);
$livePrefix = $root . '/servers/scf_gateway_startup_fixture_master_' . $livePort;
file_put_contents($livePrefix . '.upstreams.conf', "# generated by SCF Gateway\n# app=startup_fixture, role=master, port={$livePort}\n"
    . "upstream live_fixture {\n    server 127.0.0.1:{$liveBackendPort};\n}\n");
file_put_contents($livePrefix . '.server.conf', "server { listen 127.0.0.1:{$livePort}; return 200 live; }\n");
$prefix = $root . '/servers/scf_gateway_startup_fixture_master_' . $stalePort;
$staleUpstream = "# generated by SCF Gateway\n# app=startup_fixture, role=master, port={$stalePort}\n"
    . "upstream obsolete {\n    server 127.0.0.1:{$deadPort};\n}\n";
file_put_contents($prefix . '.upstreams.conf', $staleUpstream);
file_put_contents($prefix . '.server.conf', "server { listen 127.0.0.1:{$stalePort}; location / { proxy_pass http://obsolete; } }\n");
file_put_contents($root . '/nginx.conf', "worker_processes 1;\npid {$root}/nginx.pid;\nerror_log {$root}/error.log notice;\n"
    . "events { worker_connections 128; }\nhttp { access_log off; include {$root}/servers/*; }\n");
$handler = new StartupFixtureNginx($root, $binary, $port);
$passed = false;
try {
    $handler->warmup();
    checkNginx(!is_file($root . '/nginx.pid'), 'Metadata warmup must not start nginx with stale includes');
    $result = $handler->sync('register_managed_plan_activate');
    checkNginx($result['reloaded'], 'Cold start must load the generated entry');
    checkNginx(!file_exists($prefix . '.server.conf'), 'Retired same-app include must be quarantined');
    checkNginx(is_file($livePrefix . '.server.conf'), 'A same-app config with a live backend must be preserved');
    checkNginx(is_resource($occupied), 'Unrelated port owner must be preserved');
    $backups = glob($root . '/.scf-nginx-*/*.upstreams.conf.*.bak') ?: [];
    checkNginx(count($backups) === 1 && file_get_contents($backups[0]) === $staleUpstream,
        'Retired config backup must retain exact content outside the wildcard include');
    checkNginx(file_get_contents('http://127.0.0.1:' . $port) === 'old', 'New ingress must serve');
    $before = file_get_contents($root . '/servers/scf_upsteam_' . $port . '.server.conf');
    $handler->invalid = true;
    try {
        $handler->sync('rolling_restart_activate');
        throw new RuntimeException('Invalid nginx config was accepted');
    } catch (RuntimeException $error) {
        checkNginx(str_contains($error->getMessage(), 'nginx'), 'Expected nginx validation failure');
    }
    checkNginx(file_get_contents($root . '/servers/scf_upsteam_' . $port . '.server.conf') === $before,
        'Failed config must restore the previous files');
    checkNginx(file_get_contents('http://127.0.0.1:' . $port) === 'old', 'Failure must preserve live ingress');
    $slow = stream_socket_client('tcp://127.0.0.1:' . $port, $errno, $error, 1);
    stream_set_timeout($slow, 8);
    fwrite($slow, "GET /slow HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n");
    $slowResponse = fread($slow, 512);
    $handler->invalid = false;
    $handler->answer = 'new';
    $handler->sync('rolling_restart_activate');
    checkNginx(file_get_contents('http://127.0.0.1:' . $port) === 'new', 'Reload must be observed through the live entry');
    $slowResponse .= stream_get_contents($slow);
    fclose($slow);
    checkNginx(str_ends_with($slowResponse, str_repeat('old-', 512)), 'A slow response from old workers must finish across reload');
    $before = file_get_contents($root . '/servers/scf_upsteam_' . $port . '.server.conf');
    $handler->extraListenPort = $stalePort;
    try {
        $handler->sync('rolling_restart_activate');
        throw new RuntimeException('nginx accepted an unbound listener');
    } catch (RuntimeException $error) {
        checkNginx(str_contains($error->getMessage(), '入口未加载'), 'A successful reload signal must still fail if nginx cannot bind');
    }
    checkNginx(file_get_contents($root . '/servers/scf_upsteam_' . $port . '.server.conf') === $before,
        'Rejected HUP must restore on-disk config too');
    checkNginx(file_get_contents('http://127.0.0.1:' . $port) === 'new', 'Rejected HUP keeps old workers serving');
    $handler->extraListenPort = 0;
    $handler->sync('rolling_restart_activate');
    $passed = true;
    echo "PASS real nginx: stale port quarantine, rollback, rejected HUP detection, slow response across verified reload\n";
} finally {
    if (is_file($root . '/nginx.pid')) {
        $pid = (int)file_get_contents($root . '/nginx.pid');
        if ($pid > 0) {
            posix_kill($pid, SIGQUIT);
            $deadline = microtime(true) + 3;
            while (posix_kill($pid, 0) && microtime(true) < $deadline) usleep(20000);
        }
    }
    fclose($occupied);
    fclose($liveBackend);
    // Keep a failing run's private config/logs available for diagnosis.
    if ($passed) {
        foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,
            FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST) as $item) {
            $item->isDir() ? rmdir($item->getPathname()) : unlink($item->getPathname());
        }
        rmdir($root);
    } else echo "Fixture: {$root}\n";
}
