<?php
return [
    'module_style' => APP_MODULE_STYLE_MULTI,//模块风格 1:单模块;2:多模块
    'port' => 9580,
    'rpc_port' => 9680,
    'worker_num' => 8,
    'worker_memory_limit' => 256,//单worker内存使用限制(MB)
    'worker_memory_auto_restart' => false,//单worker内存超限后是否自动平滑轮换,默认关闭
    'redis_queue_memory_limit' => 1024,//redis队列管理进程内存限制(MB)
    'max_wait_time' => 30,
    'task_worker_num' => 4,
    'static_handler_locations' => ['/cp'],
    'enable_coroutine' => true,
    'max_connection' => 1024,//最大连接数
    'gateway_proxy_max_inflight' => 1024,//Gateway转发在途连接上限,超过后拒绝新的TCP转发连接
    'gateway_traffic_mode' => 'nginx',//Gateway业务流量模式: nginx(推荐,由nginx承接业务入口) / tcp(轻量TCP转发)
    'gateway_control_port' => 0,//Gateway控制面HTTP/WS监听端口,与业务端口分离,0表示业务端口+1000
    'gateway_tcp_relay_connect_timeout' => 3,//纯TCP转发模式连接upstream超时时间(秒)
    'gateway_tcp_relay_idle_timeout' => 0,//纯TCP转发模式上游空闲读超时时间(秒),0表示不主动截断空闲长连接
    'gateway_nginx_sync_enabled' => true,//由Gateway同步生成nginx upstream配置
    'gateway_nginx_reload_on_sync' => true,//同步nginx upstream配置后自动执行nginx reload/start
    'gateway_nginx_bin' => '',//nginx可执行文件路径,留空自动探测(兼容docker/homebrew/openresty)
    'gateway_nginx_conf_dir' => '',//Gateway生成的nginx配置目录,留空自动探测当前nginx include目录
    'gateway_nginx_server_name' => '_',//生成的nginx示例server_name
    'gateway_nginx_disable_global_logs' => true,//由Gateway生成http级nginx配置并关闭全局访问/错误日志
    'gateway_nginx_proxy_connect_timeout' => 3,//nginx到upstream建立连接超时时间(秒)
    'gateway_nginx_proxy_io_timeout' => 31536000,//nginx到upstream读写超时时间(秒),默认近似不限制
    'gateway_nginx_client_io_timeout' => 31536000,//客户端读写超时时间(秒),默认近似不限制
    'gateway_nginx_proxy_buffering' => true,//nginx代理缓冲开关
    'gateway_nginx_real_ip_header' => 'X-Forwarded-For',//nginx从哪个头恢复真实客户端IP
    'gateway_nginx_trusted_proxies' => ['127.0.0.1', '::1'],//哪些代理来源可被信任为真实来源头提供方
    'gateway_nginx_real_ip_recursive' => true,//是否递归解析受信代理转发链中的真实来源IP
    'max_coroutine' => 10240,//最多启动多少个协程
    'max_concurrency' => 2048,//最高并发
    'max_request_limit' => 1280,//每秒最大请求量限制,超过此值将拒绝服务
    'max_mysql_execute_limit' => 1280,//每秒最大mysql处理量限制,超过此值将拒绝服务
    'package_max_length' => 10 * 1024 * 1024,//最大请求数据限制,默认:10M
    'dashboard_password' => null,//控制台超级密码
    'redis_queue_in_master' => true,//master节点运行redis队列开关
    'redis_queue_in_slave' => false,//slave节点运行redis队列开关
    'slow_log_time' => 10000,//慢日志时间
    'redis_queue_mc' => 32,//redis队列每次取出数量
    'db_statistics_enable' => false,//开启数据库统计组件,需配置statistics和history数据库
    'db_statistics_interval' => 3,//统计数据入库扫描间隔
    'allow_cross_origin' => false,//允许跨域请求
];
