<?php

namespace Scf\Server\Proxy;

use RuntimeException;

class GatewayNginxProxyHandler {

    protected ?array $nginxRuntimeMeta = null;
    protected ?string $lastObservedRuntimeMetaSignature = null;

    public function __construct(
        protected GatewayServer $gateway,
        protected AppInstanceManager $instanceManager
    ) {
    }

    public function enabled(): bool {
        return $this->gateway->nginxProxyModeEnabled()
            || (bool)($this->gateway->serverConfig()['gateway_nginx_sync_enabled'] ?? false);
    }

    public function sync(?string $reason = null): array {
        $runtimeMeta = $this->nginxRuntimeMeta();
        $globalFile = $this->generatedGlobalFile();
        $upstreamFile = $this->generatedUpstreamFile();
        $serverFile = $this->generatedServerFile();
        $exampleFile = $this->generatedExampleServerFile();
        $globalContent = $this->renderGlobalConfig();
        $upstreamContent = $this->renderUpstreamConfig();
        $serverContent = $this->renderServerConfig();

        $globalChanged = $this->writeIfChanged($globalFile, $globalContent);
        $upstreamChanged = $this->writeIfChanged($upstreamFile, $upstreamContent);
        $serverChanged = $this->writeIfChanged($serverFile, $serverContent);

        $exampleChanged = false;
        if (!$this->nginxServerFileExists()) {
            $exampleChanged = $this->writeIfChanged($exampleFile, $serverContent);
        }

        $tested = false;
        $reloaded = false;
        if ($globalChanged || $upstreamChanged || $serverChanged || $exampleChanged) {
            $this->testNginxConfig();
            $tested = true;
            if ($this->shouldReloadNginx()) {
                $this->reloadOrStartNginx();
                $reloaded = true;
            }
        }

        return [
            'reason' => $reason ?: 'manual',
            'global_file' => $globalFile,
            'upstream_file' => $upstreamFile,
            'server_file' => $serverFile,
            'example_file' => $exampleFile,
            'global_changed' => $globalChanged,
            'upstream_changed' => $upstreamChanged,
            'server_changed' => $serverChanged,
            'example_changed' => $exampleChanged,
            'tested' => $tested,
            'reloaded' => $reloaded,
            'business_upstream_name' => $this->businessUpstreamName(),
            'control_upstream_name' => $this->controlUpstreamName(),
            'active_instances' => $this->activeInstances(),
            'runtime_meta' => $runtimeMeta,
            'runtime_meta_changed' => $this->markRuntimeMetaObserved($runtimeMeta),
        ];
    }

    protected function renderGlobalConfig(): string {
        $disableLogs = (bool)($this->gateway->serverConfig()['gateway_nginx_disable_global_logs'] ?? true);
        $proxyConnectTimeout = max(1, (int)($this->gateway->serverConfig()['gateway_nginx_proxy_connect_timeout'] ?? 3));
        $proxyIoTimeout = max(60, (int)($this->gateway->serverConfig()['gateway_nginx_proxy_io_timeout'] ?? 31536000));
        $clientIoTimeout = max(60, (int)($this->gateway->serverConfig()['gateway_nginx_client_io_timeout'] ?? $proxyIoTimeout));
        $buffering = (bool)($this->gateway->serverConfig()['gateway_nginx_proxy_buffering'] ?? true);
        $existing = $this->existingHttpDirectives();

        $lines = [
            '# generated by SCF Gateway',
            '# global http-level tuning',
        ];

        if ($disableLogs) {
            $this->appendDirectiveIfMissing($lines, $existing, 'access_log', 'access_log off;');
            $this->appendDirectiveIfMissing($lines, $existing, 'error_log', 'error_log /dev/null crit;');
        }

        $this->appendDirectiveIfMissing($lines, $existing, 'server_tokens', 'server_tokens off;');
        $this->appendDirectiveIfMissing($lines, $existing, 'sendfile', 'sendfile on;');
        $this->appendDirectiveIfMissing($lines, $existing, 'tcp_nopush', 'tcp_nopush on;');
        $this->appendDirectiveIfMissing($lines, $existing, 'tcp_nodelay', 'tcp_nodelay on;');
        $this->appendDirectiveIfMissing($lines, $existing, 'keepalive_timeout', 'keepalive_timeout 30;');
        $this->appendDirectiveIfMissing($lines, $existing, 'keepalive_requests', 'keepalive_requests 10000;');
        $this->appendDirectiveIfMissing($lines, $existing, 'reset_timedout_connection', 'reset_timedout_connection on;');
        $this->appendDirectiveIfMissing($lines, $existing, 'types_hash_max_size', 'types_hash_max_size 4096;');
        $this->appendDirectiveIfMissing($lines, $existing, 'proxy_http_version', 'proxy_http_version 1.1;');
        $this->appendDirectiveIfMissing($lines, $existing, 'proxy_request_buffering', 'proxy_request_buffering on;');
        $this->appendDirectiveIfMissing($lines, $existing, 'proxy_buffering', 'proxy_buffering ' . ($buffering ? 'on' : 'off') . ';');
        $this->appendDirectiveIfMissing($lines, $existing, 'proxy_socket_keepalive', 'proxy_socket_keepalive on;');
        $this->appendDirectiveIfMissing($lines, $existing, 'proxy_connect_timeout', 'proxy_connect_timeout ' . $proxyConnectTimeout . 's;');
        $this->appendDirectiveIfMissing($lines, $existing, 'proxy_read_timeout', 'proxy_read_timeout ' . $proxyIoTimeout . 's;');
        $this->appendDirectiveIfMissing($lines, $existing, 'proxy_send_timeout', 'proxy_send_timeout ' . $proxyIoTimeout . 's;');
        $this->appendDirectiveIfMissing($lines, $existing, 'client_body_timeout', 'client_body_timeout ' . $clientIoTimeout . 's;');
        $this->appendDirectiveIfMissing($lines, $existing, 'send_timeout', 'send_timeout ' . $clientIoTimeout . 's;');
        $lines[] = '';

        return implode("\n", $lines);
    }

    protected function renderUpstreamConfig(): string {
        $activeInstances = $this->activeInstances();
        $businessServers = $this->renderBusinessUpstreamServers($activeInstances);
        $controlHost = $this->gateway->internalControlHost();
        $controlPort = $this->gateway->controlPort();
        $businessName = $this->businessUpstreamName();
        $controlName = $this->controlUpstreamName();

        return implode("\n", [
            '# generated by SCF Gateway',
            '# do not edit manually',
            '# app=' . APP_DIR_NAME . ', role=' . SERVER_ROLE . ', port=' . $this->gateway->businessPort(),
            '',
            'upstream ' . $businessName . ' {',
            $businessServers,
            '    keepalive 128;',
            '}',
            '',
            'upstream ' . $controlName . ' {',
            '    server ' . $controlHost . ':' . $controlPort . ' max_fails=1 fail_timeout=2s;',
            '    keepalive 16;',
            '}',
            '',
        ]);
    }

    protected function renderServerConfig(): string {
        $serverName = (string)($this->gateway->serverConfig()['gateway_nginx_server_name'] ?? '_');
        $listenPort = $this->gateway->businessPort();
        $businessName = $this->businessUpstreamName();
        $controlName = $this->controlUpstreamName();
        $upgradeMapVar = '$' . $this->safeToken('scf_gateway_connection_upgrade_' . APP_DIR_NAME . '_' . SERVER_ROLE . '_' . $listenPort);
        $realIpHeader = trim((string)($this->gateway->serverConfig()['gateway_nginx_real_ip_header'] ?? 'X-Forwarded-For'));
        $realIpRecursive = (bool)($this->gateway->serverConfig()['gateway_nginx_real_ip_recursive'] ?? true);
        $trustedProxies = $this->trustedRealIpProxies();
        $realIpLines = [];
        if ($realIpHeader !== '' && $trustedProxies) {
            $realIpLines[] = '    real_ip_header ' . $realIpHeader . ';';
            foreach ($trustedProxies as $proxy) {
                $realIpLines[] = '    set_real_ip_from ' . $proxy . ';';
            }
            $realIpLines[] = '    real_ip_recursive ' . ($realIpRecursive ? 'on' : 'off') . ';';
            $realIpLines[] = '';
        }

        $staticLocationLines = $this->renderStaticLocationBlocks();
        if ($staticLocationLines) {
            $staticLocationLines[] = '';
        }

        return implode("\n", array_merge([
            'map $http_upgrade ' . $upgradeMapVar . ' {',
            "    default upgrade;",
            "    '' '';",
            '}',
            '',
            'server {',
            '    listen ' . $listenPort . ';',
            '    server_name ' . $serverName . ';',
            '',
        ], $realIpLines, [
            '    location = /dashboard.socket {',
            '        proxy_http_version 1.1;',
            '        proxy_set_header Host $host;',
            '        proxy_set_header Upgrade $http_upgrade;',
            '        proxy_set_header Connection ' . $upgradeMapVar . ';',
            '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
            '        proxy_set_header X-Forwarded-Host $host;',
            '        proxy_set_header X-Forwarded-Port $server_port;',
            '        proxy_set_header X-Forwarded-Proto $scheme;',
            '        proxy_set_header X-Real-IP $remote_addr;',
            '        proxy_pass http://' . $controlName . ';',
            '    }',
            '',
            '    location ^~ /_gateway/ {',
            '        proxy_http_version 1.1;',
            '        proxy_set_header Host $host;',
            '        proxy_set_header X-Real-IP $remote_addr;',
            '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
            '        proxy_set_header X-Forwarded-Host $host;',
            '        proxy_set_header X-Forwarded-Port $server_port;',
            '        proxy_set_header X-Forwarded-Proto $scheme;',
            '        proxy_pass http://' . $controlName . ';',
            '    }',
            '',
            '    location ^~ /~ {',
            '        proxy_http_version 1.1;',
            '        proxy_set_header Host $host;',
            '        proxy_set_header X-Real-IP $remote_addr;',
            '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
            '        proxy_set_header X-Forwarded-Host $host;',
            '        proxy_set_header X-Forwarded-Port $server_port;',
            '        proxy_set_header X-Forwarded-Proto $scheme;',
            '        proxy_pass http://' . $controlName . ';',
            '    }',
            '',
        ], $staticLocationLines, [
            '    location / {',
            '        proxy_http_version 1.1;',
            '        proxy_set_header Upgrade $http_upgrade;',
            '        proxy_set_header Connection ' . $upgradeMapVar . ';',
            '        proxy_set_header Host $host;',
            '        proxy_set_header X-Real-IP $remote_addr;',
            '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
            '        proxy_set_header X-Forwarded-Host $host;',
            '        proxy_set_header X-Forwarded-Port $server_port;',
            '        proxy_set_header X-Forwarded-Proto $scheme;',
            '        proxy_pass http://' . $businessName . ';',
            '    }',
            '}',
            '',
        ]));
    }

    protected function renderExampleServerConfig(): string {
        return "# example only; rename to .conf when ready to enable\n" . $this->renderServerConfig();
    }

    protected function renderBusinessUpstreamServers(array $instances): string {
        if (!$instances) {
            return '    server 127.0.0.1:9 down;';
        }

        $lines = [];
        foreach ($instances as $instance) {
            $host = (string)($instance['host'] ?? '127.0.0.1');
            $port = (int)($instance['port'] ?? 0);
            if ($port <= 0) {
                continue;
            }
            $weight = max(1, (int)($instance['weight'] ?? 1));
            $lines[] = '    server ' . $host . ':' . $port . ' weight=' . $weight . ' max_fails=1 fail_timeout=2s;';
        }

        return $lines ? implode("\n", $lines) : '    server 127.0.0.1:9 down;';
    }

    protected function renderStaticLocationBlocks(): array {
        $locations = (array)($this->gateway->serverConfig()['static_handler_locations'] ?? []);
        if (!$locations) {
            return [];
        }

        $publicRoot = rtrim(APP_PATH, '/') . '/public';
        $blocks = [];
        foreach ($locations as $location) {
            $path = trim((string)$location);
            if ($path === '' || $path[0] !== '/') {
                continue;
            }
            if ($this->gateway->shouldRoutePathToControlPlane($path)) {
                continue;
            }

            if ($this->looksLikeStaticFile($path)) {
                $blocks[] = '    location = ' . $path . ' {';
                $blocks[] = '        root ' . $publicRoot . ';';
                $blocks[] = '        access_log off;';
                $blocks[] = '        log_not_found off;';
                $blocks[] = '        try_files $uri =404;';
                $blocks[] = '    }';
                continue;
            }

            $normalized = rtrim($path, '/');
            if ($normalized === '') {
                $normalized = '/';
            }
            $blocks[] = '    location = ' . $normalized . ' {';
            $blocks[] = '        root ' . $publicRoot . ';';
            $blocks[] = '        access_log off;';
            $blocks[] = '        log_not_found off;';
            $blocks[] = '        try_files $uri $uri/ =404;';
            $blocks[] = '    }';
            $blocks[] = '';
            $blocks[] = '    location ^~ ' . $normalized . '/ {';
            $blocks[] = '        root ' . $publicRoot . ';';
            $blocks[] = '        access_log off;';
            $blocks[] = '        log_not_found off;';
            $blocks[] = '        try_files $uri $uri/ =404;';
            $blocks[] = '    }';
        }

        return $blocks ? array_merge($blocks, ['']) : [];
    }

    protected function looksLikeStaticFile(string $path): bool {
        $basename = basename($path);
        return $basename !== '' && str_contains($basename, '.');
    }

    protected function activeInstances(): array {
        $state = $this->instanceManager->snapshot();
        $activeVersion = (string)($state['active_version'] ?? '');
        if ($activeVersion === '') {
            return [];
        }
        $instances = (array)($state['generations'][$activeVersion]['instances'] ?? []);
        return array_values(array_filter($instances, static function (array $instance) {
            return in_array((string)($instance['status'] ?? 'offline'), ['active', 'prepared'], true)
                && (int)($instance['port'] ?? 0) > 0;
        }));
    }

    protected function businessUpstreamName(): string {
        return $this->safeToken('scf_gateway_business_' . APP_DIR_NAME . '_' . SERVER_ROLE . '_' . $this->gateway->businessPort());
    }

    protected function controlUpstreamName(): string {
        return $this->safeToken('scf_gateway_control_' . APP_DIR_NAME . '_' . SERVER_ROLE . '_' . $this->gateway->businessPort());
    }

    protected function generatedUpstreamFile(): string {
        return rtrim($this->confDir(), '/') . '/' . $this->fileBaseName() . '.upstreams.conf';
    }

    protected function generatedGlobalFile(): string {
        return rtrim($this->confDir(), '/') . '/scf_gateway.global.conf';
    }

    protected function generatedServerFile(): string {
        return rtrim($this->confDir(), '/') . '/' . $this->fileBaseName() . '.server.conf';
    }

    protected function generatedExampleServerFile(): string {
        return rtrim($this->confDir(), '/') . '/' . $this->fileBaseName() . '.server.example';
    }

    protected function confDir(): string {
        $configured = trim((string)($this->gateway->serverConfig()['gateway_nginx_conf_dir'] ?? ''));
        if ($configured !== '') {
            return rtrim($configured, '/');
        }
        return rtrim((string)($this->nginxRuntimeMeta()['conf_dir'] ?? '/etc/nginx/conf.d'), '/');
    }

    protected function nginxBin(): string {
        $configured = trim((string)($this->gateway->serverConfig()['gateway_nginx_bin'] ?? ''));
        if ($configured !== '') {
            return $configured;
        }
        return (string)($this->nginxRuntimeMeta()['bin'] ?? 'nginx');
    }

    protected function fileBaseName(): string {
        return $this->safeToken('scf_gateway_' . APP_DIR_NAME . '_' . SERVER_ROLE . '_' . $this->gateway->businessPort());
    }

    protected function writeIfChanged(string $path, string $content): bool {
        $dir = dirname($path);
        if (!is_dir($dir) && !@mkdir($dir, 0777, true) && !is_dir($dir)) {
            throw new RuntimeException('创建nginx配置目录失败: ' . $dir);
        }
        $existing = is_file($path) ? (string)file_get_contents($path) : null;
        if ($existing === $content) {
            return false;
        }
        if (@file_put_contents($path, $content) === false) {
            throw new RuntimeException('写入nginx配置失败: ' . $path);
        }
        return true;
    }

    protected function testNginxConfig(): void {
        $bin = $this->nginxBin();
        $command = escapeshellarg($bin) . ' -t';
        $confPath = (string)($this->nginxRuntimeMeta()['conf_path'] ?? '');
        if ($confPath !== '') {
            $command .= ' -c ' . escapeshellarg($confPath);
        }
        $command .= ' 2>&1';
        exec($command, $output, $code);
        if ($code !== 0) {
            throw new RuntimeException("nginx 配置检测失败:\n" . implode("\n", $output));
        }
    }

    protected function reloadNginx(): void {
        $bin = $this->nginxBin();
        $command = escapeshellarg($bin) . ' -s reload';
        $confPath = (string)($this->nginxRuntimeMeta()['conf_path'] ?? '');
        if ($confPath !== '') {
            $command .= ' -c ' . escapeshellarg($confPath);
        }
        $command .= ' 2>&1';
        exec($command, $output, $code);
        if ($code !== 0) {
            throw new RuntimeException("nginx 重载失败:\n" . implode("\n", $output));
        }
    }

    protected function startNginx(): void {
        $bin = $this->nginxBin();
        $command = escapeshellarg($bin);
        $confPath = (string)($this->nginxRuntimeMeta()['conf_path'] ?? '');
        if ($confPath !== '') {
            $command .= ' -c ' . escapeshellarg($confPath);
        }
        $command .= ' 2>&1';
        exec($command, $output, $code);
        if ($code !== 0) {
            throw new RuntimeException("nginx 启动失败:\n" . implode("\n", $output));
        }
    }

    protected function reloadOrStartNginx(): void {
        if ($this->isNginxRunning()) {
            $this->reloadNginx();
            return;
        }
        $this->startNginx();
    }

    protected function isNginxRunning(): bool {
        $pidPath = (string)($this->nginxRuntimeMeta()['pid_path'] ?? '');
        if ($pidPath === '') {
            $pidPath = '/run/nginx.pid';
        }
        $pid = is_file($pidPath) ? (int)trim((string)file_get_contents($pidPath)) : 0;
        if ($pid <= 0) {
            return false;
        }
        return function_exists('posix_kill') ? @posix_kill($pid, 0) : is_dir('/proc/' . $pid);
    }

    protected function shouldReloadNginx(): bool {
        return $this->gateway->nginxProxyModeEnabled()
            || (bool)($this->gateway->serverConfig()['gateway_nginx_reload_on_sync'] ?? false);
    }

    protected function nginxServerFileExists(): bool {
        return is_file($this->generatedServerFile());
    }

    protected function safeToken(string $value): string {
        $value = preg_replace('/[^a-zA-Z0-9_]+/', '_', $value) ?: 'scf_gateway';
        return trim($value, '_');
    }

    protected function trustedRealIpProxies(): array {
        $configured = $this->gateway->serverConfig()['gateway_nginx_trusted_proxies'] ?? ['127.0.0.1', '::1'];
        if (is_string($configured)) {
            $configured = array_map('trim', explode(',', $configured));
        }
        if (!is_array($configured)) {
            return ['127.0.0.1', '::1'];
        }
        $trusted = [];
        foreach ($configured as $proxy) {
            $proxy = trim((string)$proxy);
            if ($proxy !== '') {
                $trusted[] = $proxy;
            }
        }
        return $trusted ?: ['127.0.0.1', '::1'];
    }

    protected function nginxRuntimeMeta(): array {
        if ($this->nginxRuntimeMeta !== null) {
            return $this->nginxRuntimeMeta;
        }

        $bin = $this->detectNginxBinary();
        $meta = [
            'bin' => $bin,
            'conf_path' => '',
            'pid_path' => '',
            'conf_dir' => '',
        ];

        $command = escapeshellarg($bin) . ' -V 2>&1';
        exec($command, $output, $code);
        if ($code === 0 || $output) {
            $versionInfo = implode("\n", $output);
            $meta['conf_path'] = $this->extractNginxBuildArg($versionInfo, 'conf-path');
            $meta['pid_path'] = $this->extractNginxBuildArg($versionInfo, 'pid-path');
        }

        $meta['conf_dir'] = $this->detectNginxConfDir((string)$meta['conf_path']);
        return $this->nginxRuntimeMeta = $meta;
    }

    protected function detectNginxBinary(): string {
        $candidates = [];
        $fromPath = trim((string)shell_exec('command -v nginx 2>/dev/null'));
        if ($fromPath !== '') {
            $candidates[] = $fromPath;
        }
        $candidates = array_merge($candidates, [
            '/usr/sbin/nginx',
            '/usr/local/sbin/nginx',
            '/usr/local/openresty/nginx/sbin/nginx',
            '/opt/homebrew/opt/nginx/bin/nginx',
        ]);
        foreach (array_unique($candidates) as $candidate) {
            if ($candidate !== '' && is_file($candidate) && is_executable($candidate)) {
                return $candidate;
            }
        }
        return $fromPath !== '' ? $fromPath : 'nginx';
    }

    protected function extractNginxBuildArg(string $versionInfo, string $key): string {
        if (preg_match('/--' . preg_quote($key, '/') . '=([^\\s]+)/', $versionInfo, $matches)) {
            return trim((string)$matches[1], "\"'");
        }
        return '';
    }

    protected function detectNginxConfDir(string $confPath): string {
        $confDir = $confPath !== '' ? dirname($confPath) : '/etc/nginx';
        $candidates = [];
        if ($confPath !== '' && is_file($confPath)) {
            $content = (string)file_get_contents($confPath);
            if (preg_match_all('/^\\s*include\\s+([^;]+);/m', $content, $matches)) {
                foreach ($matches[1] as $include) {
                    $include = trim((string)$include, "\"' ");
                    if ($include === '') {
                        continue;
                    }
                    if (!str_starts_with($include, '/')) {
                        $include = $confDir . '/' . $include;
                    }
                    $candidates[] = str_contains($include, '*') ? dirname($include) : $include;
                }
            }
        }

        $candidates = array_merge($candidates, [
            $confDir . '/conf.d',
            $confDir . '/servers',
            '/etc/nginx/conf.d',
            '/usr/local/openresty/nginx/conf/conf.d',
            '/opt/homebrew/etc/nginx/servers',
        ]);

        foreach (array_unique($candidates) as $candidate) {
            if (is_dir($candidate)) {
                return rtrim($candidate, '/');
            }
        }

        return rtrim($confDir . '/conf.d', '/');
    }

    protected function existingHttpDirectives(): array {
        $confPath = (string)($this->nginxRuntimeMeta()['conf_path'] ?? '');
        if ($confPath === '' || !is_file($confPath)) {
            return [];
        }
        $content = (string)file_get_contents($confPath);
        $found = [];
        preg_match_all('/^\\s*([a-z_]+)\\s+.+;/mi', $content, $matches);
        foreach ($matches[1] ?? [] as $name) {
            $name = strtolower(trim((string)$name));
            if ($name !== '') {
                $found[$name] = true;
            }
        }
        return $found;
    }


    protected function appendDirectiveIfMissing(array &$lines, array $existing, string $name, string $directive): void {
        if (!isset($existing[strtolower($name)])) {
            $lines[] = $directive;
        }
    }

    protected function markRuntimeMetaObserved(array $meta): bool {
        $signature = md5(json_encode([
            'bin' => (string)($meta['bin'] ?? ''),
            'conf_path' => (string)($meta['conf_path'] ?? ''),
            'conf_dir' => (string)($meta['conf_dir'] ?? ''),
            'pid_path' => (string)($meta['pid_path'] ?? ''),
        ], JSON_UNESCAPED_SLASHES));
        if ($this->lastObservedRuntimeMetaSignature === $signature) {
            return false;
        }
        $this->lastObservedRuntimeMetaSignature = $signature;
        return true;
    }
}
